### ISSUE TITLE
Is there a configuration for rk3328 chip?

### ISSUE THREAD

**Issue by sprhawk** [JeffyCN/yocto-manifests#1]
There are many hardware there using rk3328, but no support in yocto?

**Comment by JeffyCN** [comment]
Supporting new boards is not that hard, but the thing is i don't have any rk3328 devices...
And i'm happy to provide some patches if anyone willing to try ;)

**Comment by JeffyCN** [comment]
I've uploaded rk3328 evb patches, that should work(i guess)

**Comment by sprhawk** [comment]
> I've uploaded rk3328 evb patches, that should work(i guess)

Cool
