### ISSUE TITLE
Unable to build rockchip-rk3328-evb

### ISSUE THREAD

**Issue by irenekravets** [JeffyCN/yocto-manifests#2]
I cloned the repos using rockchip-rk3328-evb.xml manifest, dunfell branch  The "repo init" and "repo sync" commands worked OK.  However, when I try to build, I get some repo fetch errors (please see the attached buildlog.txt).  I also tried the master branch of the manifest file, but got a different build error.
Which branch of manifest repo should I be using to fetch rockchip-rk3328-evb files?  Why am I getting this error?

[buildlog.txt](https://github.com/JeffyCN/yocto-manifests/files/5263569/buildlog.txt)

**Comment by JeffyCN** [comment]
I've created mirrors for those missing things, try:
https://github.com/JeffyCN/mirrors
(check the readme about how to use it)
