### ISSUE TITLE
failed to fetch

### ISSUE THREAD

**Issue by firexx** [JeffyCN/yocto-manifests#3]
I tried master dunfell and zeus branches. all of them failed to fetch 
git://github.com/rockchip-linux/linux-rga.git because such repository does not exists.

**Comment by JeffyCN** [comment]
check this mirror repo（of rockchip git server in china）：
https://github.com/JeffyCN/mirrors

**Comment by firexx** [comment]
Hi Jeffy, yes i did that(mirrors) before i wrote this issue. and followed your description. but it does not work...
which git server in china you mean?
Edit:
I found, it was my fault. but you misused the git branches as separated git repositories. ;-)
issue can be closed

**Comment by JeffyCN** [comment]
yes, i did that(to keep it simple), follow the readme should be fine(old version of meta-rockchip needs some extra changes(check note in the readme))
