### ISSUE TITLE
[Honister] Failed to bitbake core-image-minimal for rockchip-rk3566-evb.conf

### ISSUE THREAD

**Issue by namtrino** [JeffyCN/yocto-manifests#4]
It failed because cannot fetch source from github.com/JeffyCN as show below.

> ERROR: rockchip-librga-1.0-r0 do_fetch: Fetcher failure: Unable to find revision 1e2f0dbb838de3512a8a29143196d7b5e460e1ca in branch linux-rga-im2d even from upstream
> ERROR: rockchip-librga-1.0-r0 do_fetch: Fetcher failure for URL: 'git://github.com/JeffyCN/mirrors.git;protocol=https;branch=linux-rga-im2d;'. Unable to fetch URL from any source.
> ERROR: Logfile of failure stored in: /opt/jeffycn/yocto/honister/build/tmp/work/armv8a-poky-linux/rockchip-librga/1.0-r0/temp/log.do_fetch.694319
> ERROR: rockchip-libmali-1.0-r0 do_unpack: Unpack failure for URL: 'git://github.com/JeffyCN/mirrors.git;protocol=https;branch=libmali;'. No up to date source found: clone directory not available or not up to date: /opt/jeffycn/yocto/honister/build/../packages/git2/github.com.JeffyCN.mirrors.git; shallow clone not enabled
> ERROR: Task (/opt/jeffycn/yocto/honister/build/../meta-rockchip/recipes-graphics/rockchip-librga/rockchip-librga.bb:do_fetch) failed with exit code '1'
> ERROR: Logfile of failure stored in: /opt/jeffycn/yocto/honister/build/tmp/work/rockchip_rk3566_evb-poky-linux/rockchip-libmali/1.0-r0/temp/log.do_unpack.827609
> ERROR: Task (/opt/jeffycn/yocto/honister/build/../meta-rockchip/recipes-graphics/rockchip-libmali/rockchip-libmali.bb:do_unpack) failed with exit code '1'
> ERROR: linux-libc-headers-4.19-custom-r0 do_unpack: Unpack failure for URL: 'git://github.com/JeffyCN/mirrors.git;protocol=https;nobranch=1;branch=kernel-4.19-2022_01_10;'. No up to date source found: clone directory not available or not up to date: /opt/jeffycn/yocto/honister/build/../packages/git2/github.com.JeffyCN.mirrors.git; shallow clone not enabled
> ERROR: Logfile of failure stored in: /opt/jeffycn/yocto/honister/build/tmp/work/armv8a-poky-linux/linux-libc-headers/4.19-custom-r0/temp/log.do_unpack.827607
> ERROR: linux-rockchip-4.19-r0 do_unpack: Unpack failure for URL: 'git://github.com/JeffyCN/mirrors.git;protocol=https;nobranch=1;branch=kernel-4.19-2022_01_10;'. No up to date source found: clone directory not available or not up to date: /opt/jeffycn/yocto/honister/build/../packages/git2/github.com.JeffyCN.mirrors.git; shallow clone not enabled
> ERROR: Logfile of failure stored in: /opt/jeffycn/yocto/honister/build/tmp/work/rockchip_rk3566_evb-poky-linux/linux-rockchip/4.19-r0/temp/log.do_unpack.827603
> ERROR: Task (/opt/jeffycn/yocto/honister/build/../meta-rockchip/recipes-kernel/linux-libc-headers/linux-libc-headers_4.19-custom.bb:do_unpack) failed with exit code '1'
> ERROR: Task (/opt/jeffycn/yocto/honister/build/../meta-rockchip/recipes-kernel/linux/linux-rockchip_4.19.bb:do_unpack) failed with exit code '1'
> ERROR: rockchip-mpp-1.0-r0 do_unpack: Unpack failure for URL: 'git://github.com/JeffyCN/mirrors.git;protocol=https;nobranch=1;branch=mpp-dev-2022_05_23;'. No up to date source found: clone directory not available or not up to date: /opt/jeffycn/yocto/honister/build/../packages/git2/github.com.JeffyCN.mirrors.git; shallow clone not enabled
> ERROR: Logfile of failure stored in: /opt/jeffycn/yocto/honister/build/tmp/work/armv8a-poky-linux/rockchip-mpp/1.0-r0/temp/log.do_unpack.827621
> ERROR: Task (/opt/jeffycn/yocto/honister/build/../meta-rockchip/recipes-multimedia/rockchip-mpp/rockchip-mpp.bb:do_unpack) failed with exit code '1'

![image](https://user-images.githubusercontent.com/1842779/216211400-88e4e4f3-729d-49d3-9e40-d0eebbf89efb.png)

**Comment by JeffyCN** [comment]
the internal default branch changed, i've reuploaded it

**Comment by namtrino** [comment]
Hi, thank you but still have 2 failed below.

1. linux-libc-headers
> ERROR: linux-libc-headers-4.19-custom-r0 do_unpack: Unpack failure for URL: 'git://github.com/JeffyCN/mirrors.git;protocol=https;nobranch=1;branch=kernel-4.19-2022_01_10;'.
> No up to date source found: clone directory not available or not up to date: /opt/jeffycn/yocto/honister/build/../packages/git2/github.com.JeffyCN.mirrors.git; shallow clone not enabled
> 

2. linux kernel
> ERROR: linux-rockchip-4.19-r0 do_unpack: Unpack failure for URL: 'git://github.com/JeffyCN/mirrors.git;protocol=https;nobranch=1;branch=kernel-4.19-2022_01_10;'. 
> No up to date source found: clone directory not available or not up to date: `/opt/jeffycn/yocto/honister/build/../packages/git2/github.com.JeffyCN.mirrors.git; shallow clone not enabled
>

**Comment by JeffyCN** [comment]
try to remove packages dir and retry

**Comment by namtrino** [comment]
After remove  packages dir and retry still error with the message below.

> ERROR: linux-libc-headers-4.19-custom-r0 do_unpack: Unpack failure for URL: 'git://github.com/JeffyCN/mirrors.git;protocol=https;nobranch=1;branch=kernel-4.19-2022_01_10;'. No up to date source found:

![image](https://user-images.githubusercontent.com/1842779/216637957-8c513395-3947-46f1-abff-420c9c8d623a.png)

**Comment by JeffyCN** [comment]
the source is valid:https://github.com/JeffyCN/mirrors/tree/kernel-4.19-2022_01_10

it's your local environment issue, try to setup a new environmnt(starting from repo init) or clear the packages and build/*cache or bitbake linux-libc-headers -c cleanall

**Comment by namtrino** [comment]
After I try with new directory and the patch below, it can build. 
Thank you very much for your help.

>  % git diff recipes-graphics/rockchip-librga/rockchip-librga.bb
> diff --git a/recipes-graphics/rockchip-librga/rockchip-librga.bb b/recipes-graphics/rockchip-librga/rockchip-librga.bb
> index 1316ae1..e760ec6 100644
> --- a/recipes-graphics/rockchip-librga/rockchip-librga.bb
> +++ b/recipes-graphics/rockchip-librga/rockchip-librga.bb
> @@ -14,7 +14,7 @@ inherit freeze-rev local-git
>  SRC_URI = " \
>         git://github.com/JeffyCN/mirrors.git;protocol=https;branch=linux-rga-im2d; \
>  "
> -SRCREV = "1e2f0dbb838de3512a8a29143196d7b5e460e1ca"
> +SRCREV = "080709bfce0fe07f15292f59fa34397f25408de6"
>  S = "${WORKDIR}/git"
> 
>  inherit meson pkgconfig

**Comment by namtrino** [comment]
Is it possible to reupload rockchip-librga repo too?

**Comment by JeffyCN** [comment]
done :)

**Comment by namtrino** [comment]
Build successful, thank you very much Jeffy :)
